### ISSUE TITLE
FR10. Being able to edit post after it’s posted 

### ISSUE THREAD

**Issue by Jainil16** [WSU-4110/Wayne_Book_Rental#10]
|FR10. Being able to edit post after it’s posted |
|---|
|**Goal**: To ensure that each stakeholder get the accurate information. 
**Stakeholders:** Students, Professors |
| **Description:** Once a book has been posted the person who originally posted it will be able to go back and edit the book details and the renting price if required. This ensures accuracy.  |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/22/2020
|  **Priority:** Low |

**Comment by akhibrshd** [comment]
George will research and start working on this feature
