### ISSUE TITLE
FR11. Contact renter via phone and email 

### ISSUE THREAD

**Issue by Jainil16** [WSU-4110/Wayne_Book_Rental#11]
|FR11. Contact renter via phone and email |
|---|
|**Goal**: Users can able to communicate other party by different communication method. 
**Stakeholders:** Students, Professors |
| **Description:** When creating an account, the users will input their contact info. The email will be a required field but cell number will be optional. The person who wants to make a deal can directly reach out the renter via email or phone from our application. |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/22/2020
|  **Priority:** Medium|

**Comment by akhibrshd** [comment]
AK will take care
