### ISSUE TITLE
FR12. Connection to PayPal 

### ISSUE THREAD

**Issue by Jainil16** [WSU-4110/Wayne_Book_Rental#12]
|FR12. Connection to PayPal |
|---|
|**Goal**: Connect to PayPal API
**Stakeholders:** Students, Professors, administrators|
| **Description:** We will connect to PayPal API so the transactions can be made on our application that makes it safe and as PayPal is a safer option to avoid scammers, it will be a safe option to have. The user will put the PayPal account that they want to receive the payment in and we will do the connection.  |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/22/2020
|  **Priority:** Low |

**Comment by akhibrshd** [comment]
Akhib will research
