### ISSUE TITLE
FR13. Able to add book to a wishlist of some sort  

### ISSUE THREAD

**Issue by Jainil16** [WSU-4110/Wayne_Book_Rental#13]
| FR13. Able to add book to a wishlist of some sort |
|---|
|**Goal**: To create a wishlist if the book is not found.
**Stakeholders:** Students, Professors|
| **Description:** If the people don’t get their book that the were looking to rent, they can create a wishlist. This wishlist keeps all the info and when they come back for looking up the books, they can easily find the details. Also, people who posted books for renting out they can reach out if they see others have this book in their wishlist.  |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/22/2020
|  **Priority:** Low |

**Comment by akhibrshd** [comment]
Jainil will take care
