### ISSUE TITLE
FR14. Searching by specific category 

### ISSUE THREAD

**Issue by Jainil16** [WSU-4110/Wayne_Book_Rental#14]
|FR14. Searching by specific category |
|---|
|**Goal**: Searching by category such as author and ISBN 
**Stakeholders:** Students, Professors|
| **Description:** In the first stage the user is only able to search by book name. At this stage the user will be able to search using different categories such as author name, ISBN and subject. |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/22/2020
|  **Priority:** Low |

**Comment by akhibrshd** [comment]
Jad taking care of it
