### ISSUE TITLE
FR15. Renting history by specific person 

### ISSUE THREAD

**Issue by Jainil16** [WSU-4110/Wayne_Book_Rental#15]
|FR15. Renting history by specific person|
|---|
|**Goal**: People can see their renting history.
**Stakeholders:** Students, professors, administrators |
| **Description:** People will be able to see their renting history on their profile. This helps them keep track and for us to have a record. |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/22/2020
|  **Priority:** Low |

**Comment by akhibrshd** [comment]
George will take care
