### ISSUE TITLE
NR16.  Encryption using hashing (Security) 

### ISSUE THREAD

**Issue by Jainil16** [WSU-4110/Wayne_Book_Rental#16]
|NR16.  Encryption using hashing (Security)|
|---|
|**Goal**: Encrypt all user information when they sign up for service.
**Stakeholders:** Students, Professors|
| **Description:** The API will utilize the hashing industry standard as a form of a security in order to secure user data from any harmful suspects. Any sensitive info taken into the DB will be hashed and secured. |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/22/2020
|  **Priority:** 2|

**Comment by rexdivakar** [comment]
Assign it to me I would like to work on it
