### ISSUE TITLE
FR6. Search bar for searching up books

### ISSUE THREAD

**Issue by Jainil16** [WSU-4110/Wayne_Book_Rental#6]
|FR6.  Search bar for searching up books|
|---|
|**Goal**: Stakeholder can search the book they want if they cannot find it in post feed.
**Stakeholders:** Students, Professors|
| **Description:** The feed will have a search bar that lets the user search for books using keywords like book name and ISBN number. Because the feed shows most recently posted books it might be hard for some users to look for desired books, this search bar will help them find the desired book. |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/22/2020
|  **Priority:** High |

**Comment by akhibrshd** [comment]
Jad is working on this
