### ISSUE TITLE
FR7. Filtering books by category

### ISSUE THREAD

**Issue by Jainil16** [WSU-4110/Wayne_Book_Rental#7]
|FR7.  Filtering book by category|
|---|
|**Goal**: Stakeholder can filter the category by using specific categories.
**Stakeholders:** Students, Professors |
| **Description:** This feature lets the user to filter the feed into specific categories such as only for specific subject or author. This helps the reduce all the books that they think are not necessary and only see books related to their subject. |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/22/2020
|  **Priority:** Medium |

**Comment by akhibrshd** [comment]
Akhib and Jad pairing up
