### ISSUE TITLE
FR8. Rating profiles and reviewing renters

### ISSUE THREAD

**Issue by Jainil16** [WSU-4110/Wayne_Book_Rental#8]
|FR8.  Rating profiles and reviewing renters|
|---|
|**Goal**: After each smooth ending both parties will have option to give their feedback in form of reviews.
**Stakeholders:** Students, Professors|
| **Description:** User will be able to review their experience with the other users. They can go to other users’ profile and put their review on their account. This helps the other users to view the reviews and decide if they want to go make a deal or not. |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/22/2020
|  **Priority:** Medium |

**Comment by akhibrshd** [comment]
AK will take research and start working on it
