### ISSUE TITLE
FR9. Reporting Profiles

### ISSUE THREAD

**Issue by Jainil16** [WSU-4110/Wayne_Book_Rental#9]
|FR9. Reporting Profiles|
|---|
|**Goal**: To make sure that no fraud happens on this web application  
**Stakeholders:** Students, Professors |
| **Description:** If a user experiences any bad experience or they suspicious activities from any other profile they will have the option to report that user. Once reported we will investigate the case and if found guilty will take necessary steps against the user. This will keep our application free from scammers.  |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/22/2020
|  **Priority:** Medium |

**Comment by akhibrshd** [comment]
Jainil is working on this.
